branch-defaults:
  master:
    environment: nest-api-template-production
    group_suffix: null
  staging:
    environment: nest-api-template-staging
    group_suffix: null
global:
  application_name: nest-api-template
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Docker running on 64bit Amazon Linux 2
  default_region: ap-northeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
