export enum Education {
  ELEMENTARY = 'ELEMENTARY',
  JUNIOR_HIGH = 'JUNIOR_HIGH',
  SENIOR_HIGH = 'SENIOR_HIGH',
  VOCATIONAL_HIGH = 'VOCATIONAL_HIGH',
  UNIVERSITY = 'UNIVERSITY',
  MASTER = 'MASTER',
  DOCTORAL = 'DOCTORAL',
}
